//! ESI access and local persistence.
//!
//! `EsiManagerCore` wraps the ESI API (`LiveEsiApi`) for the SSO authorization
//! flow, token refresh and location / portrait queries, and reads and writes
//! characters, corporations and alliances in the local SQLite player database (see
//! `player_database`). With the `crypted-db` feature the database is encrypted
//! (SQLCipher) with a key derived from a per-machine identifier.

use crate::objects::AuthData;
use crate::objects::{Alliance, AuthClaims, AuthorizeInfo, Character, CharacterPublicInfo};
use crate::objects::{Corporation, TokenSet};
use http_body_util::{BodyExt, Empty};
use hyper::body::Body;
use hyper_tls::HttpsConnector;
use rfesi::prelude::*;
use rusqlite::vtab::array;
use rusqlite::*;
use std::collections::HashMap;
use std::path::{Path, PathBuf};
//use hyper::body::Bytes;
use bytes::Bytes;
use hyper_util::{client::legacy::Client, rt::TokioExecutor};

//#[cfg(feature = "crypted-db")]
//use uuid::Uuid;

#[cfg(all(target_os = "windows", feature = "crypted-db"))]
use windows::{Storage::Streams::DataReader, System::Profile::SystemIdentification};

#[cfg(all(target_os = "macos", feature = "crypted-db"))]
use objc2_core_foundation::{CFAllocator, CFString};

#[cfg(all(target_os = "macos", feature = "crypted-db"))]
use objc2_io_kit::{
    IOObjectRelease, IORegistryEntryCreateCFProperty, IOServiceGetMatchingService,
    IOServiceMatching, kIOMainPortDefault,
};

use self::player_database::PlayerDatabase;
pub use self::player_database::{SCHEMA_VERSION, SchemaStatus};
pub mod player_database;

#[cfg(feature = "crypted-db")]
const FALLBACK_UNIQUE_ID: &str = "t313/sc0p3";

/// Network boundary towards the CCP servers (SSO + ESI).
///
/// Every operation that talks to CCP goes through this trait so the
/// application logic in [`EsiManagerCore`] can be unit tested without
/// network access using the `MockEsiApi` generated by mockall in test
/// builds. The production implementation is [`LiveEsiApi`].
#[cfg_attr(test, mockall::automock)]
#[allow(async_fn_in_trait)]
pub trait EsiApi: Send {
    /// Builds the SSO authorization URL (and PKCE verifier when the
    /// `native-auth-flow` feature is enabled). Pure, no network involved.
    fn authorize_url(&self) -> Result<AuthorizeInfo, String>;
    /// Whether the underlying client holds a complete token set.
    fn has_token_state(&self) -> bool;
    /// Returns the current token set, if complete.
    fn current_tokens(&self) -> Option<TokenSet>;
    /// Loads a character's token set into the client, so the next
    /// authenticated call is made as that character.
    fn set_tokens(&mut self, tokens: &TokenSet);
    /// Exchanges an OAuth code for tokens and returns the JWT claims.
    async fn authenticate(
        &mut self,
        code: &str,
        verifier: Option<String>,
    ) -> Result<Option<AuthClaims>, String>;
    /// Refreshes the OAuth metadata document from the SSO server.
    async fn update_spec(&mut self) -> Result<(), String>;
    /// Exchanges a refresh token for a new token set.
    async fn refresh_access_token(&mut self, refresh_token: &str) -> Result<TokenSet, String>;
    /// Fetches the public info of a character from ESI.
    async fn get_character_public_info(
        &mut self,
        character_id: i32,
    ) -> Result<CharacterPublicInfo, String>;
    /// Fetches the public info of a corporation from ESI.
    async fn get_corporation_public_info(
        &mut self,
        corporation_id: i32,
    ) -> Result<Corporation, String>;
    /// Fetches the info of an alliance from ESI.
    async fn get_alliance_info(&mut self, alliance_id: i32) -> Result<Alliance, String>;
    /// Fetches the URL of the 128x128 character portrait from ESI.
    async fn get_character_portrait_url(&mut self, character_id: i32) -> Result<String, String>;
    /// Fetches the current solar system of a character from ESI.
    async fn get_location(&mut self, character_id: i32) -> Result<i32, String>;
}

/// ESI endpoints Telescope uses, as `(operationId, path)` in the format of
/// the old Swagger spec, which is what `rfesi` resolves operation ids
/// against.
///
/// CCP removed `/latest/swagger.json` on 11 August 2026 (it now answers
/// 404), and `rfesi` 0.50.2 still downloads its spec from there, so every
/// ESI call failed with "Invalid HTTP status code received: 404". Embedding
/// the few routes we need removes that network dependency; the routes
/// themselves still answer (versioned by the `X-Compatibility-Date` header
/// `rfesi` sends). A new endpoint used through `rfesi` must be added here.
const ESI_ENDPOINTS: &[(&str, &str)] = &[
    ("get_characters_character_id", "/characters/{character_id}/"),
    (
        "get_characters_character_id_portrait",
        "/characters/{character_id}/portrait/",
    ),
    (
        "get_characters_character_id_location",
        "/characters/{character_id}/location/",
    ),
    (
        "get_corporations_corporation_id",
        "/corporations/{corporation_id}/",
    ),
    ("get_alliances_alliance_id", "/alliances/{alliance_id}/"),
];

/// Builds the minimal Swagger-shaped spec (`{"paths": {path: {"get":
/// {"operationId": ..}}}}`) for [`ESI_ENDPOINTS`].
fn embedded_spec_json() -> serde_json::Value {
    let paths: serde_json::Map<String, serde_json::Value> = ESI_ENDPOINTS
        .iter()
        .map(|(op_id, path)| {
            (
                (*path).to_owned(),
                serde_json::json!({ "get": { "operationId": op_id } }),
            )
        })
        .collect();
    serde_json::json!({ "paths": paths })
}

/// Production [`EsiApi`] implementation backed by `rfesi`.
#[derive(Clone)]
pub struct LiveEsiApi {
    esi: Esi,
}

impl EsiApi for LiveEsiApi {
    #[tracing::instrument(skip(self))]
    fn authorize_url(&self) -> Result<AuthorizeInfo, String> {
        self.esi
            .get_authorize_url()
            .map(|info| AuthorizeInfo {
                url: info.authorization_url,
                pkce_verifier: info.pkce_verifier,
            })
            .map_err(|e| e.to_string())
    }

    #[tracing::instrument(skip(self))]
    fn has_token_state(&self) -> bool {
        self.esi.access_expiration.is_some()
            && self.esi.access_token.is_some()
            && self.esi.refresh_token.is_some()
    }

    #[tracing::instrument(skip_all)]
    fn set_tokens(&mut self, tokens: &TokenSet) {
        self.esi.access_token = Some(tokens.token.clone());
        self.esi.refresh_token = Some(tokens.refresh_token.clone());
        self.esi.access_expiration = tokens
            .expiration
            .map(|expiration| expiration.timestamp_millis());
    }

    #[tracing::instrument(skip(self))]
    fn current_tokens(&self) -> Option<TokenSet> {
        Some(TokenSet {
            token: self.esi.access_token.clone()?,
            refresh_token: self.esi.refresh_token.clone()?,
            expiration: chrono::DateTime::from_timestamp_millis(self.esi.access_expiration?),
        })
    }

    // `skip_all`, not just `skip(self)`: `code` is the OAuth authorization
    // code and `verifier` the PKCE verifier -- same secrecy rule
    // `EsiManagerCore::auth_user` already applies one level up, for the
    // same reason.
    #[tracing::instrument(skip_all)]
    async fn authenticate(
        &mut self,
        code: &str,
        verifier: Option<String>,
    ) -> Result<Option<AuthClaims>, String> {
        match self.esi.authenticate(code, verifier).await {
            Ok(Some(claims)) => Ok(Some(AuthClaims {
                name: claims.name,
                sub: claims.sub,
            })),
            Ok(None) => Ok(None),
            Err(t_error) => Err(t_error.to_string()),
        }
    }

    /// No-op: the spec is embedded at construction (see [`ESI_ENDPOINTS`]),
    /// because the Swagger URL `rfesi` would download it from is gone.
    #[tracing::instrument(skip(self))]
    async fn update_spec(&mut self) -> Result<(), String> {
        Ok(())
    }

    // `refresh_token` is itself a credential -- never recorded, same as
    // `code`/`verifier` above.
    #[tracing::instrument(skip(self, refresh_token))]
    async fn refresh_access_token(&mut self, refresh_token: &str) -> Result<TokenSet, String> {
        self.esi
            .refresh_access_token(Some(refresh_token))
            .await
            .map_err(|t_error| t_error.to_string())?;
        self.current_tokens()
            .ok_or_else(|| String::from("incomplete token state after refresh"))
    }

    #[tracing::instrument(skip(self))]
    async fn get_character_public_info(
        &mut self,
        character_id: i32,
    ) -> Result<CharacterPublicInfo, String> {
        self.esi
            .group_character()
            .get_public_info(character_id)
            .await
            .map(|info| CharacterPublicInfo {
                corporation_id: info.corporation_id,
                alliance_id: info.alliance_id,
            })
            .map_err(|t_error| t_error.to_string())
    }

    #[tracing::instrument(skip(self))]
    async fn get_corporation_public_info(
        &mut self,
        corporation_id: i32,
    ) -> Result<Corporation, String> {
        self.esi
            .group_corporation()
            .get_public_info(corporation_id)
            .await
            .map(|info| Corporation {
                id: corporation_id,
                name: info.name,
            })
            .map_err(|t_error| t_error.to_string())
    }

    #[tracing::instrument(skip(self))]
    async fn get_alliance_info(&mut self, alliance_id: i32) -> Result<Alliance, String> {
        self.esi
            .group_alliance()
            .get_info(alliance_id)
            .await
            .map(|info| Alliance {
                id: alliance_id,
                name: info.name,
            })
            .map_err(|t_error| t_error.to_string())
    }

    #[tracing::instrument(skip(self))]
    async fn get_character_portrait_url(&mut self, character_id: i32) -> Result<String, String> {
        self.esi
            .group_character()
            .get_portrait(character_id)
            .await
            .map_err(|t_error| t_error.to_string())?
            .px128x128
            .ok_or_else(|| String::from("no 128x128 portrait available"))
    }

    #[tracing::instrument(skip(self))]
    async fn get_location(&mut self, character_id: i32) -> Result<i32, String> {
        self.esi
            .group_location()
            .get_location(character_id)
            .await
            .map(|location| location.solar_system_id)
            .map_err(|t_error| t_error.to_string())
    }
}

/// ESI manager: orchestrates authentication state, ESI calls and the local
/// player database. Generic over the [`EsiApi`] network boundary.
#[derive(Clone)]
pub struct EsiManagerCore<T: EsiApi> {
    api: T,
    /// OAuth token set of each linked character, by character id (an EVE
    /// SSO token only works for the character that logged in).
    pub auth: HashMap<i32, AuthData>,
    /// What opening the player database found (see
    /// [`PlayerDatabase::ensure_schema`]); `None` if it couldn't be opened.
    pub schema_status: Option<SchemaStatus>,
    pub characters: Vec<Character>,
    pub path: PathBuf,
    pub active_character: Option<i32>,
}

/// The production ESI manager, backed by the live CCP servers.
pub type EsiManager = EsiManagerCore<LiveEsiApi>;

impl<T: EsiApi> EsiManagerCore<T> {
    #[tracing::instrument(skip(self))]
    pub(crate) fn get_standard_connection(&self) -> Result<Connection, Error> {
        let mut flags = OpenFlags::default();
        flags.set(OpenFlags::SQLITE_OPEN_NO_MUTEX, false);
        flags.set(OpenFlags::SQLITE_OPEN_FULL_MUTEX, true);
        let connection = Connection::open_with_flags(self.path.clone(), flags)?;

        // we add the carray module disguised as rarray in rusqlite
        array::load_module(&connection)?;

        let query = "PRAGMA journey_mode=WAL;";
        let mut statement = connection.prepare(query)?;
        let _ = statement.execute([])?;

        #[cfg(feature = "crypted-db")]
        {
            #[cfg(target_os = "windows")]
            let value_txt = self.get_windows_unique_id().unwrap();
            #[cfg(target_os = "macos")]
            let value_txt = self.get_macos_unique_id().unwrap();
            #[cfg(target_os = "linux")]
            let value_txt = self.get_linux_unique_id().unwrap();
            //let uuid = Uuid::new_v5(&Uuid::NAMESPACE_DNS, value_txt.as_bytes());
            //let query = ["PRAGMA key = '", uuid.to_string().as_str(), "'"].concat();
            let query = ["PRAGMA key = '", value_txt.as_str(), "'"].concat();
            let mut statement = connection.prepare(query.as_str())?;

            let _ = statement.query([])?;
        }

        statement.finalize()?;
        Ok(connection)
    }

    #[cfg(all(target_os = "macos", feature = "crypted-db"))]
    fn get_macos_unique_id(&self) -> Result<String, String> {
        // macOS unique ID
        unsafe {
            // 1. Obtener el entry del IORegistry para la plataforma
            let matching = IOServiceMatching(c"IOPlatformExpertDevice".as_ptr())
                .map(|matching| (&matching).into());
            let entry = IOServiceGetMatchingService(kIOMainPortDefault, matching);

            if entry != 0 {
                // 2. Construir la clave como CFString
                let key = CFString::from_str("IOPlatformSerialNumber");

                // 3. Llamar a IORegistryEntryCreateCFProperty
                let cf_value = IORegistryEntryCreateCFProperty(
                    entry,
                    Some(&key),
                    None::<&CFAllocator>, // usar el allocator por defecto
                    0,                    // options = 0
                );

                // 4. Liberar el entry
                IOObjectRelease(entry);

                // 5. Convertir el CFType resultante a CFString y luego a String de Rust
                if let Some(retained) = cf_value
                    && let Ok(cf_str) = retained.downcast::<CFString>()
                {
                    return Ok(cf_str.to_string());
                }
            }
        }
        Err(String::from(FALLBACK_UNIQUE_ID))
    }

    #[cfg(all(target_os = "linux", feature = "crypted-db"))]
    fn get_linux_unique_id(&self) -> Result<String, String> {
        // Placeholder implementation for Linux unique ID
        Ok(String::from(FALLBACK_UNIQUE_ID))
    }

    #[cfg(all(target_os = "windows", feature = "crypted-db"))]
    fn get_windows_unique_id(&self) -> Result<String, String> {
        // this get a unique ID for the user, and its used to generate a unique key
        // for the database encryption
        match SystemIdentification::GetSystemIdForPublisher() {
            Ok(info) => {
                if let Ok(id_buffer) = info.Id()
                    && let Ok(reader) = DataReader::FromBuffer(&id_buffer)
                {
                    // reading bytes from ID IBuffer
                    if let Ok(length) = id_buffer.Length() {
                        let mut bytes = vec![0u8; length as usize];
                        if let Ok(()) = reader.ReadBytes(&mut bytes) {
                            return Ok(String::from_utf8_lossy(&bytes).into_owned());
                        }
                    }
                }
                Err(String::from(FALLBACK_UNIQUE_ID))
            }
            Err(_) => Err(String::from(FALLBACK_UNIQUE_ID)),
        }
    }

    // Alliance
    #[tracing::instrument(skip(self))]
    pub fn write_alliance(&mut self, alliance: &Alliance) -> Result<usize, Error> {
        let conn = self.get_standard_connection().unwrap();

        let players = PlayerDatabase::select_alliance(&conn, vec![alliance.id])?;
        let rows = if !players.is_empty() {
            PlayerDatabase::update_alliance(&conn, alliance)?
        } else {
            PlayerDatabase::insert_alliance(&conn, alliance)?
        };
        Ok(rows)
    }

    #[tracing::instrument(skip(self))]
    pub fn read_alliance(
        &mut self,
        alliance_vec: Option<Vec<i32>>,
    ) -> Result<Vec<Alliance>, Error> {
        let conn = match self.get_standard_connection() {
            Ok(connection) => connection,
            Err(error) => {
                return Err(error);
            }
        };

        let result = if let Some(id_ally) = alliance_vec {
            PlayerDatabase::select_alliance(&conn, id_ally)?
        } else {
            PlayerDatabase::select_alliance(&conn, vec![])?
        };
        Ok(result)
    }

    #[tracing::instrument(skip(self))]
    pub fn remove_alliance(&mut self, alliance_vec: Option<Vec<i32>>) -> Result<usize, Error> {
        let conn = match self.get_standard_connection() {
            Ok(connection) => connection,
            Err(error) => {
                return Err(error);
            }
        };

        let result = if let Some(id_ally) = alliance_vec {
            PlayerDatabase::delete_alliance(&conn, id_ally)?
        } else {
            PlayerDatabase::delete_alliance(&conn, vec![])?
        };
        Ok(result)
    }

    // Corporation
    #[tracing::instrument(skip(self))]
    pub fn write_corporation(&mut self, corp: &Corporation) -> Result<usize, Error> {
        let conn = match self.get_standard_connection() {
            Ok(connection) => connection,
            Err(error) => {
                return Err(error);
            }
        };

        let corps = PlayerDatabase::select_corporation(&conn, vec![corp.id])?;
        let rows = if !corps.is_empty() {
            PlayerDatabase::update_corporation(&conn, corp)?
        } else {
            PlayerDatabase::insert_corporation(&conn, corp)?
        };
        Ok(rows)
    }

    #[tracing::instrument(skip(self))]
    pub fn read_corporation(
        &mut self,
        corporation_vec: Option<Vec<i32>>,
    ) -> Result<Vec<Corporation>, Error> {
        let conn = match self.get_standard_connection() {
            Ok(connection) => connection,
            Err(error) => {
                return Err(error);
            }
        };

        let result = if let Some(id_corp) = corporation_vec {
            PlayerDatabase::select_corporation(&conn, id_corp)?
        } else {
            PlayerDatabase::select_corporation(&conn, vec![])?
        };
        Ok(result)
    }

    #[tracing::instrument(skip(self))]
    pub fn remove_corporation(
        &mut self,
        corporation_vec: Option<Vec<i32>>,
    ) -> Result<usize, Error> {
        let conn = match self.get_standard_connection() {
            Ok(connection) => connection,
            Err(error) => {
                return Err(error);
            }
        };

        let result = if let Some(id_ally) = corporation_vec {
            PlayerDatabase::delete_corporation(&conn, id_ally)?
        } else {
            PlayerDatabase::delete_corporation(&conn, vec![])?
        };
        Ok(result)
    }

    //Characters
    #[tracing::instrument(skip(self))]
    pub fn write_character(&mut self, char: &Character) -> Result<usize, Error> {
        let conn = match self.get_standard_connection() {
            Ok(connection) => connection,
            Err(error) => {
                return Err(error);
            }
        };
        //let conn = self.get_standard_connection().unwrap();

        // first we need to assure that Corporation and alliance exists on database
        if let Some(corp) = &char.corp {
            let _ = self.write_corporation(corp)?;
        }

        if let Some(alliance) = &char.alliance {
            let _ = self.write_alliance(alliance)?;
        }

        let players = PlayerDatabase::select_characters(&conn, vec![char.id])?;
        let rows = if !players.is_empty() {
            PlayerDatabase::update_character(&conn, char)?
        } else {
            PlayerDatabase::insert_character(&conn, char)?
        };
        Ok(rows)
    }

    #[tracing::instrument(skip(self))]
    pub fn read_characters(&mut self, char_vec: Option<Vec<i32>>) -> Result<Vec<Character>, Error> {
        let conn = match self.get_standard_connection() {
            Ok(connection) => connection,
            Err(error) => {
                return Err(error);
            }
        };

        let result;
        if let Some(id_chars) = char_vec {
            result = PlayerDatabase::select_characters(&conn, id_chars)?;
        } else {
            result = PlayerDatabase::select_characters(&conn, vec![])?;
        };
        Ok(result)
    }

    /// Takes over the token set of `character_id` (and the API client) from
    /// `other`, typically a clone of this manager that completed
    /// [`Self::auth_user`] for that character on a background thread. The
    /// other characters' tokens and the character list are left untouched.
    pub fn adopt_session(&mut self, other: Self, character_id: i32) {
        let Self { api, mut auth, .. } = other;
        self.api = api;
        if let Some(character_auth) = auth.remove(&character_id) {
            self.auth.insert(character_id, character_auth);
        }
    }

    /// Reloads every character's token set from the database, e.g. in a
    /// long-lived clone (the watchdog) after another clone stored a new one.
    #[tracing::instrument(skip(self))]
    pub fn reload_auth(&mut self) -> Result<(), Error> {
        let conn = self.get_standard_connection()?;
        self.auth = PlayerDatabase::select_auth(&conn)?;
        Ok(())
    }

    #[tracing::instrument(skip(self))]
    pub fn remove_characters(&mut self, char_vec: Option<Vec<i32>>) -> Result<usize, Error> {
        let conn = self.get_standard_connection()?;
        let ids = char_vec.unwrap_or_default();
        let transaction = conn.unchecked_transaction()?;
        PlayerDatabase::delete_auth(&transaction, ids.clone())?;
        let result = PlayerDatabase::delete_characters(&transaction, ids.clone())?;
        transaction.commit()?;
        for id in ids {
            self.auth.remove(&id);
        }
        Ok(result)
    }

    /// Shared constructor: initializes the local database (creating it when
    /// missing) and loads the stored characters and authentication data.
    #[tracing::instrument(skip(api))]
    fn build(api: T, database_path: &Path) -> Self {
        let mut obj = EsiManagerCore {
            api,
            auth: HashMap::new(),
            schema_status: None,
            characters: Vec::new(),
            path: database_path.to_path_buf(),
            active_character: None,
        };

        // Create the schema if the file has none (new or empty file) or run
        // the pending migration scripts if it is older; see
        // `PlayerDatabase::ensure_schema`. The caller reports
        // `schema_status` to the user.
        match obj.get_standard_connection() {
            Ok(conn) => {
                match PlayerDatabase::ensure_schema(&conn) {
                    Ok(status) => {
                        if status != SchemaStatus::UpToDate {
                            tracing::warn!(path = %obj.path.display(), ?status, "player database schema");
                        }
                        obj.schema_status = Some(status);
                    }
                    Err(t_error) => tracing::error!(
                        path = %obj.path.display(),
                        error = %t_error,
                        "could not prepare the player database"
                    ),
                }
                let _ = conn.close();
            }
            Err(t_error) => tracing::error!(
                path = %obj.path.display(),
                error = %t_error,
                "could not open the player database"
            ),
        }
        if let Ok(conn) = obj.get_standard_connection() {
            // load existing players
            if let Ok(chars) = PlayerDatabase::select_characters(&conn, vec![]) {
                obj.characters = chars;
            }
            match PlayerDatabase::select_auth(&conn) {
                Ok(auth) => obj.auth = auth,
                Err(t_error) => tracing::error!(
                    error = %t_error,
                    "could not load the characters' tokens"
                ),
            }
        }
        obj
    }

    /// Builds a manager over a custom [`EsiApi`] implementation (tests).
    #[cfg(test)]
    pub(crate) fn with_api(api: T, database_path: &Path) -> Self {
        Self::build(api, database_path)
    }

    /// Returns the SSO authorization URL to start the OAuth flow.
    #[tracing::instrument(skip(self))]
    pub fn get_authorize_url(&self) -> Result<AuthorizeInfo, String> {
        self.api.authorize_url()
    }

    /// Refreshes the OAuth metadata document from the SSO server.
    #[tracing::instrument(skip(self))]
    pub async fn update_spec(&mut self) -> Result<(), String> {
        self.api.update_spec().await
    }

    /// Current solar system of a character, called as that character (its
    /// own token set is loaded into the client first).
    #[tracing::instrument(skip(self))]
    pub async fn get_location(&mut self, player_id: i32) -> Result<i32, String> {
        if !self.valid_token(player_id).await {
            return Err(String::from("Invalid Token"));
        }
        let auth = &self.auth[&player_id];
        self.api.set_tokens(&TokenSet {
            token: auth.token.clone(),
            refresh_token: auth.refresh_token.clone(),
            expiration: auth.expiration,
        });
        self.api.get_location(player_id).await
    }

    /// Whether the character has a token set that is still valid for at
    /// least 20 seconds.
    #[tracing::instrument(skip(self))]
    pub async fn valid_token(&self, character_id: i32) -> bool {
        let Some(auth) = self.auth.get(&character_id) else {
            return false;
        };
        if auth.token.is_empty() || auth.refresh_token.is_empty() {
            return false;
        }
        auth.expiration
            .is_some_and(|expire| (expire - chrono::Utc::now()).num_seconds() >= 20)
    }

    /// Gets a new access token for the character with its refresh token,
    /// and stores it.
    #[tracing::instrument(skip(self))]
    pub async fn refresh_token(&mut self, character_id: i32) -> Result<usize, String> {
        let refresh_token = match self.auth.get(&character_id) {
            Some(auth) if !auth.refresh_token.is_empty() => auth.refresh_token.clone(),
            _ => return Err(String::from("No refresh token for this character")),
        };
        let tokens = self.api.refresh_access_token(&refresh_token).await?;
        let auth = AuthData {
            token: tokens.token,
            expiration: tokens.expiration,
            refresh_token: tokens.refresh_token,
        };
        let conn = self
            .get_standard_connection()
            .map_err(|t_error| t_error.to_string())?;
        PlayerDatabase::save_auth(&conn, character_id, &auth)
            .map_err(|t_error| t_error.to_string())?;
        self.auth.insert(character_id, auth);
        Ok(0)
    }

    #[tokio::main(flavor = "current_thread")]
    #[tracing::instrument]
    pub async fn get_player_photo(url: &str) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
        let https = HttpsConnector::new();
        let client = Client::builder(TokioExecutor::new()).build::<_, Empty<Bytes>>(https);

        let mut res = client.get(url.parse()?).await?;
        //assert_eq!(res.status(), 200);
        let mut photo: Vec<u8> = vec![];
        if res.status() == 200 {
            while !res.is_end_stream() {
                if let Some(data) = res
                    .body_mut()
                    .frame()
                    .await
                    .unwrap()
                    .expect("No data")
                    .data_mut()
                {
                    photo.extend_from_slice(data.as_ref());
                }
            }
        }
        Ok(photo)
    }

    #[tracing::instrument(skip_all)]
    pub async fn auth_user(
        &mut self,
        _auth_info: AuthorizeInfo,
        oauth_data: (String, String),
    ) -> Result<Option<Character>, Box<dyn std::error::Error + Send + Sync>> {
        #[cfg(not(feature = "native-auth-flow"))]
        let verifier = None;

        #[cfg(feature = "native-auth-flow")]
        let verifier = _auth_info.pkce_verifier;

        let claims_option = self
            .api
            .authenticate(oauth_data.0.as_str(), verifier)
            .await?;
        if let Some(claims) = claims_option {
            let mut player = Character::new();
            //character name
            player.name = claims.name;
            //character id, from the "CHARACTER:EVE:<id>" subject claim
            player.id = claims
                .sub
                .split(':')
                .nth(2)
                .and_then(|id| id.parse::<i32>().ok())
                .ok_or("invalid character id in authentication claims")?;
            // The client now holds this character's tokens; keep them for
            // this character only (every character has its own).
            let tokens = self
                .api
                .current_tokens()
                .ok_or("incomplete token set after authentication")?;
            let auth = AuthData {
                token: tokens.token,
                expiration: tokens.expiration,
                refresh_token: tokens.refresh_token,
            };
            self.api.update_spec().await?;
            let public_info = self.api.get_character_public_info(player.id).await?;
            let corp = self
                .api
                .get_corporation_public_info(public_info.corporation_id)
                .await?;
            player.corp = Some(corp);
            if let Some(ally_id) = public_info.alliance_id {
                let ally = self.api.get_alliance_info(ally_id).await?;
                player.alliance = Some(ally);
            }
            player.photo = Some(self.api.get_character_portrait_url(player.id).await?);
            player.location = self.api.get_location(player.id).await?;

            self.write_character(&player)?;
            let conn = self.get_standard_connection()?;
            PlayerDatabase::save_auth(&conn, player.id, &auth)?;
            self.auth.insert(player.id, auth);
            Ok(Some(player))
        } else {
            Ok(None)
        }
    }
}

impl EsiManagerCore<LiveEsiApi> {
    #[tracing::instrument(skip(_client_secret))]
    pub fn new(
        useragent: &str,
        client_id: &str,
        _client_secret: &str,
        callback_url: &str,
        scope: Vec<&str>,
        database_path: &Path,
    ) -> Self {
        // `rfesi`'s `Spec` type isn't exported, so it is named through
        // inference from `EsiBuilder::spec`; the JSON is built by us, so a
        // failure here is a programming error.
        let spec = serde_json::from_value(embedded_spec_json())
            .expect("embedded ESI spec must match rfesi's Spec shape");

        #[cfg(not(feature = "native-auth-flow"))]
        let esi = EsiBuilder::new()
            .user_agent(useragent)
            .client_id(client_id)
            .client_secret(_client_secret)
            .callback_url(callback_url)
            .scope(scope.join(" ").as_str())
            .spec(Some(spec))
            .build()
            .unwrap();

        #[cfg(feature = "native-auth-flow")]
        let esi = EsiBuilder::new()
            .user_agent(useragent)
            .client_id(client_id)
            .callback_url(callback_url)
            .enable_application_authentication(true)
            .scope(scope.join(" ").as_str())
            .spec(Some(spec))
            .build()
            .unwrap();

        Self::build(LiveEsiApi { esi }, database_path)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicUsize, Ordering};

    static COUNTER: AtomicUsize = AtomicUsize::new(0);

    /// Returns a unique temporary database path for the given test.
    fn temp_db_path(test_name: &str) -> PathBuf {
        let id = COUNTER.fetch_add(1, Ordering::SeqCst);
        std::env::temp_dir().join(format!(
            "webb_test_{}_{}_{}.db",
            test_name,
            std::process::id(),
            id
        ))
    }

    /// Builds an EsiManager backed by a fresh temporary database.
    fn test_manager(test_name: &str) -> (EsiManager, PathBuf) {
        let path = temp_db_path(test_name);
        let manager = EsiManager::new(
            "telescope-test (test@example.com)",
            "test-client-id",
            "test-client-secret",
            "http://localhost:8000/login",
            vec!["publicData"],
            &path,
        );
        (manager, path)
    }

    fn cleanup(path: &Path) {
        let _ = std::fs::remove_file(path);
    }

    fn sample_character() -> Character {
        let mut character = Character::new();
        character.id = 90000001;
        character.name = String::from("Test Pilot");
        character.corp = Some(Corporation {
            id: 98000001,
            name: String::from("Acme Corp"),
        });
        character.alliance = Some(Alliance {
            id: 99000001,
            name: String::from("Acme Alliance"),
        });
        character.photo = Some(String::from(
            "https://images.evetech.net/characters/90000001/portrait",
        ));
        character.last_logon = chrono::DateTime::from_timestamp(1750000000, 0).unwrap();
        character.location = 30000001;
        character
    }

    #[test]
    fn new_creates_database_and_starts_empty() {
        let (mut manager, path) = test_manager("new");

        assert!(path.exists());
        assert!(manager.characters.is_empty());
        assert_eq!(manager.active_character, None);
        assert!(manager.read_characters(None).unwrap().is_empty());
        assert!(manager.read_corporation(None).unwrap().is_empty());
        assert!(manager.read_alliance(None).unwrap().is_empty());

        cleanup(&path);
    }

    #[tokio::test]
    async fn valid_token_is_false_without_authentication() {
        let (manager, path) = test_manager("valid_token");
        assert!(!manager.valid_token(90000001).await);
        cleanup(&path);
    }

    // Regression test: a database file that exists but has no tables used
    // to be left as is, and the first auth update then panicked with
    // "no such table: metadata".
    #[test]
    fn new_repairs_an_existing_database_file_without_tables() {
        let path = temp_db_path("empty_file");
        std::fs::write(&path, b"").unwrap();
        let mut manager = EsiManager::new(
            "telescope-test (test@example.com)",
            "test-client-id",
            "test-client-secret",
            "http://localhost:8000/login",
            vec!["publicData"],
            &path,
        );
        assert_eq!(manager.schema_status, Some(SchemaStatus::Created));
        let mut character = Character::new();
        character.id = 7;
        character.name = String::from("Pilot");
        assert_eq!(manager.write_character(&character).unwrap(), 1);
        let conn = manager.get_standard_connection().unwrap();
        assert!(PlayerDatabase::save_auth(&conn, 7, &AuthData::new()).is_ok());
        cleanup(&path);
    }

    // The Swagger spec URL rfesi downloads from answers 404 since
    // 11 August 2026; the embedded spec must resolve every endpoint we use
    // without any network access.
    #[test]
    fn embedded_spec_resolves_every_endpoint_offline() {
        let (manager, path) = test_manager("embedded_spec");
        for (op_id, expected) in ESI_ENDPOINTS {
            let resolved = manager.api.esi.get_endpoint_for_op_id(op_id).unwrap();
            // rfesi strips the leading slash before appending to the base URL.
            assert_eq!(format!("/{resolved}"), *expected);
        }
        assert_eq!(
            manager
                .api
                .esi
                .get_endpoint_for_op_id("get_characters_character_id_portrait")
                .unwrap()
                .replace("{character_id}", "42"),
            "characters/42/portrait/"
        );
        cleanup(&path);
    }

    #[test]
    fn adopt_session_takes_only_that_characters_tokens() {
        let (mut manager, path) = test_manager("adopt_session");
        let mut kept = Character::new();
        kept.id = 1;
        manager.characters.push(kept);
        let mut first = AuthData::new();
        first.token = String::from("first-token");
        manager.auth.insert(1, first.clone());

        let mut background = manager.clone();
        background.characters.clear();
        // A stale copy of character 1's tokens must not overwrite ours.
        background.auth.insert(1, AuthData::new());
        let mut second = AuthData::new();
        second.token = String::from("second-token");
        background.auth.insert(2, second.clone());

        manager.adopt_session(background, 2);
        assert_eq!(manager.auth[&1], first);
        assert_eq!(manager.auth[&2], second);
        assert_eq!(manager.characters.len(), 1);
        cleanup(&path);
    }

    #[test]
    fn corporation_write_read_update_remove() {
        let (mut manager, path) = test_manager("corporation");
        let corp = Corporation {
            id: 98000001,
            name: String::from("Acme Corp"),
        };

        // insert
        assert_eq!(manager.write_corporation(&corp).unwrap(), 1);
        assert_eq!(manager.read_corporation(None).unwrap(), vec![corp.clone()]);
        assert_eq!(
            manager.read_corporation(Some(vec![corp.id])).unwrap(),
            vec![corp.clone()]
        );

        // update (writing an existing id keeps a single row)
        let renamed = Corporation {
            id: corp.id,
            name: String::from("Renamed Corp"),
        };
        assert_eq!(manager.write_corporation(&renamed).unwrap(), 1);
        assert_eq!(manager.read_corporation(None).unwrap(), vec![renamed]);

        // remove
        assert_eq!(manager.remove_corporation(Some(vec![corp.id])).unwrap(), 1);
        assert!(manager.read_corporation(None).unwrap().is_empty());
        assert_eq!(manager.remove_corporation(None).unwrap(), 0);

        cleanup(&path);
    }

    #[test]
    fn alliance_write_read_update_remove() {
        let (mut manager, path) = test_manager("alliance");
        let alliance = Alliance {
            id: 99000001,
            name: String::from("Acme Alliance"),
        };

        // insert
        assert_eq!(manager.write_alliance(&alliance).unwrap(), 1);
        assert_eq!(manager.read_alliance(None).unwrap(), vec![alliance.clone()]);
        assert_eq!(
            manager.read_alliance(Some(vec![alliance.id])).unwrap(),
            vec![alliance.clone()]
        );

        // update
        let renamed = Alliance {
            id: alliance.id,
            name: String::from("Renamed Alliance"),
        };
        assert_eq!(manager.write_alliance(&renamed).unwrap(), 1);
        assert_eq!(manager.read_alliance(None).unwrap(), vec![renamed]);

        // remove
        assert_eq!(manager.remove_alliance(Some(vec![alliance.id])).unwrap(), 1);
        assert!(manager.read_alliance(None).unwrap().is_empty());
        assert_eq!(manager.remove_alliance(None).unwrap(), 0);

        cleanup(&path);
    }

    #[test]
    fn character_write_read_update_remove() {
        let (mut manager, path) = test_manager("character");
        let character = sample_character();

        // insert (also persists its corporation and alliance)
        assert_eq!(manager.write_character(&character).unwrap(), 1);
        assert_eq!(
            manager.read_characters(None).unwrap(),
            vec![character.clone()]
        );
        assert_eq!(manager.characters.len(), 0); // read from database, not memory
        assert_eq!(manager.read_corporation(None).unwrap().len(), 1);
        assert_eq!(manager.read_alliance(None).unwrap().len(), 1);

        // update
        let mut renamed = character.clone();
        renamed.name = String::from("Renamed Pilot");
        renamed.location = 30000002;
        assert_eq!(manager.write_character(&renamed).unwrap(), 1);
        assert_eq!(manager.read_characters(None).unwrap(), vec![renamed]);

        // remove
        assert_eq!(
            manager.remove_characters(Some(vec![character.id])).unwrap(),
            1
        );
        assert!(manager.read_characters(None).unwrap().is_empty());
        assert_eq!(manager.remove_characters(None).unwrap(), 0);

        cleanup(&path);
    }

    #[test]
    fn character_read_by_ids_filters_results() {
        let (mut manager, path) = test_manager("character_filter");
        let character = sample_character();
        manager.write_character(&character).unwrap();

        assert_eq!(
            manager.read_characters(Some(vec![character.id])).unwrap(),
            vec![character]
        );
        assert!(
            manager
                .read_characters(Some(vec![12345]))
                .unwrap()
                .is_empty()
        );

        cleanup(&path);
    }

    // -----------------------------------------------------------------
    // Mock-based tests (no CCP servers involved)
    // -----------------------------------------------------------------

    /// Builds an EsiManagerCore backed by a MockEsiApi and a fresh temporary
    /// database.
    fn mock_manager(test_name: &str, mock: MockEsiApi) -> (EsiManagerCore<MockEsiApi>, PathBuf) {
        let path = temp_db_path(test_name);
        let mut mock = mock;
        // Loading a character's tokens into the client has no observable
        // effect on the mock; allow it everywhere.
        mock.expect_set_tokens().returning(|_| ());
        let manager = EsiManagerCore::with_api(mock, &path);
        (manager, path)
    }

    /// Character the mocked sessions belong to (see `sample_claims`).
    const PILOT: i32 = 90000001;

    /// Simulates a fully authenticated session for [`PILOT`].
    fn authenticate_session(manager: &mut EsiManagerCore<MockEsiApi>, seconds_valid: i64) {
        manager.auth.insert(
            PILOT,
            AuthData {
                token: String::from("access-token"),
                refresh_token: String::from("refresh-token"),
                expiration: Some(
                    chrono::Utc::now() + chrono::Duration::try_seconds(seconds_valid).unwrap(),
                ),
            },
        );
    }

    fn sample_tokens() -> TokenSet {
        TokenSet {
            token: String::from("new-access-token"),
            refresh_token: String::from("new-refresh-token"),
            expiration: Some(chrono::Utc::now() + chrono::Duration::try_seconds(3600).unwrap()),
        }
    }

    fn sample_authorize_info() -> AuthorizeInfo {
        AuthorizeInfo {
            url: String::from("https://login.eveonline.com/v2/oauth/authorize/?x=1"),
            pkce_verifier: None,
        }
    }

    fn sample_claims() -> AuthClaims {
        AuthClaims {
            name: String::from("Test Pilot"),
            sub: String::from("CHARACTER:EVE:90000001"),
        }
    }

    #[tokio::test]
    async fn get_location_requires_valid_token() {
        let mut mock = MockEsiApi::new();
        mock.expect_has_token_state().returning(|| false);
        // The ESI endpoint must never be reached without a valid token.
        mock.expect_get_location().never();
        let (mut manager, path) = mock_manager("loc_no_token", mock);

        let result = manager.get_location(90000001).await;
        assert_eq!(result, Err(String::from("Invalid Token")));

        cleanup(&path);
    }

    #[tokio::test]
    async fn get_location_returns_solar_system_id() {
        let mut mock = MockEsiApi::new();
        mock.expect_has_token_state().returning(|| true);
        mock.expect_get_location()
            .with(mockall::predicate::eq(90000001))
            .times(1)
            .returning(|_| Ok(30000142));
        let (mut manager, path) = mock_manager("loc_ok", mock);
        authenticate_session(&mut manager, 3600);

        let result = manager.get_location(90000001).await;
        assert_eq!(result, Ok(30000142));

        cleanup(&path);
    }

    #[tokio::test]
    async fn get_location_propagates_api_error() {
        let mut mock = MockEsiApi::new();
        mock.expect_has_token_state().returning(|| true);
        mock.expect_get_location()
            .returning(|_| Err(String::from("ESI unavailable")));
        let (mut manager, path) = mock_manager("loc_err", mock);
        authenticate_session(&mut manager, 3600);

        let result = manager.get_location(90000001).await;
        assert_eq!(result, Err(String::from("ESI unavailable")));

        cleanup(&path);
    }

    #[tokio::test]
    async fn refresh_token_updates_and_persists_tokens() {
        let tokens = sample_tokens();
        let expected_expiration = tokens.expiration;
        let mut mock = MockEsiApi::new();
        mock.expect_refresh_access_token()
            .withf(|refresh_token: &str| refresh_token == "old-refresh-token")
            .times(1)
            .returning(move |_| Ok(tokens.clone()));
        let (mut manager, path) = mock_manager("refresh_ok", mock);
        let mut pilot = Character::new();
        pilot.id = PILOT;
        pilot.name = String::from("Test Pilot");
        manager.write_character(&pilot).unwrap();
        let mut old = AuthData::new();
        old.refresh_token = String::from("old-refresh-token");
        manager.auth.insert(PILOT, old);
        let mut other = AuthData::new();
        other.token = String::from("other-token");
        manager.auth.insert(1, other.clone());

        assert_eq!(manager.refresh_token(PILOT).await, Ok(0));
        let refreshed = &manager.auth[&PILOT];
        assert_eq!(refreshed.token, "new-access-token");
        assert_eq!(refreshed.refresh_token, "new-refresh-token");
        assert_eq!(refreshed.expiration, expected_expiration);
        // Other characters keep their own tokens.
        assert_eq!(manager.auth[&1], other);

        // The new token set must be persisted for that character.
        let conn = manager.get_standard_connection().unwrap();
        let stored = PlayerDatabase::select_auth(&conn).unwrap();
        assert_eq!(stored[&PILOT].token, "new-access-token");
        assert_eq!(stored[&PILOT].refresh_token, "new-refresh-token");

        cleanup(&path);
    }

    #[tokio::test]
    async fn refresh_token_failure_leaves_state_untouched() {
        let mut mock = MockEsiApi::new();
        mock.expect_refresh_access_token()
            .returning(|_| Err(String::from("invalid_grant")));
        let (mut manager, path) = mock_manager("refresh_err", mock);
        let mut auth = AuthData::new();
        auth.token = String::from("access-token");
        auth.refresh_token = String::from("old-refresh-token");
        manager.auth.insert(PILOT, auth.clone());

        assert!(manager.refresh_token(PILOT).await.is_err());
        assert_eq!(manager.auth[&PILOT], auth);

        cleanup(&path);
    }

    #[tokio::test]
    async fn refresh_token_without_tokens_is_an_error() {
        let mut mock = MockEsiApi::new();
        mock.expect_refresh_access_token().never();
        let (mut manager, path) = mock_manager("refresh_none", mock);

        assert!(manager.refresh_token(PILOT).await.is_err());

        cleanup(&path);
    }

    #[tokio::test]
    async fn auth_user_assembles_and_persists_character() {
        let mut seq = mockall::Sequence::new();
        let mut mock = MockEsiApi::new();
        mock.expect_authenticate()
            .times(1)
            .in_sequence(&mut seq)
            .returning(|_, _| Ok(Some(sample_claims())));
        // The new character's tokens are always taken from the client.
        mock.expect_current_tokens()
            .times(1)
            .returning(|| Some(sample_tokens()));
        mock.expect_update_spec()
            .times(1)
            .in_sequence(&mut seq)
            .returning(|| Ok(()));
        mock.expect_get_character_public_info()
            .with(mockall::predicate::eq(90000001))
            .times(1)
            .in_sequence(&mut seq)
            .returning(|_| {
                Ok(CharacterPublicInfo {
                    corporation_id: 98000001,
                    alliance_id: Some(99000001),
                })
            });
        mock.expect_get_corporation_public_info()
            .with(mockall::predicate::eq(98000001))
            .times(1)
            .in_sequence(&mut seq)
            .returning(|_| {
                Ok(Corporation {
                    id: 98000001,
                    name: String::from("Acme Corp"),
                })
            });
        mock.expect_get_alliance_info()
            .with(mockall::predicate::eq(99000001))
            .times(1)
            .in_sequence(&mut seq)
            .returning(|_| {
                Ok(Alliance {
                    id: 99000001,
                    name: String::from("Acme Alliance"),
                })
            });
        mock.expect_get_character_portrait_url()
            .with(mockall::predicate::eq(90000001))
            .times(1)
            .in_sequence(&mut seq)
            .returning(|_| Ok(String::from("https://images/pilot.png")));
        mock.expect_get_location()
            .with(mockall::predicate::eq(90000001))
            .times(1)
            .in_sequence(&mut seq)
            .returning(|_| Ok(30000142));
        let (mut manager, path) = mock_manager("auth_full", mock);

        let player = manager
            .auth_user(
                sample_authorize_info(),
                (String::from("oauth-code"), String::from("oauth-state")),
            )
            .await
            .unwrap()
            .expect("a character must be returned");

        assert_eq!(player.id, 90000001);
        assert_eq!(player.name, "Test Pilot");
        assert_eq!(player.corp.unwrap().name, "Acme Corp");
        assert_eq!(player.alliance.unwrap().name, "Acme Alliance");
        assert_eq!(player.photo.unwrap(), "https://images/pilot.png");
        assert_eq!(player.location, 30000142);

        // Character and tokens must be persisted.
        assert_eq!(manager.read_characters(None).unwrap().len(), 1);
        assert_eq!(manager.auth[&PILOT].token, "new-access-token");
        let conn = manager.get_standard_connection().unwrap();
        assert_eq!(
            PlayerDatabase::select_auth(&conn).unwrap()[&PILOT].token,
            "new-access-token"
        );

        cleanup(&path);
    }

    #[tokio::test]
    async fn auth_user_without_claims_returns_none() {
        let mut mock = MockEsiApi::new();
        mock.expect_authenticate()
            .times(1)
            .returning(|_, _| Ok(None));
        // No other ESI call is allowed once the claims are missing.
        mock.expect_get_character_public_info().never();
        mock.expect_get_location().never();
        let (mut manager, path) = mock_manager("auth_none", mock);

        let result = manager
            .auth_user(
                sample_authorize_info(),
                (String::from("oauth-code"), String::from("oauth-state")),
            )
            .await
            .unwrap();
        assert!(result.is_none());
        assert!(manager.read_characters(None).unwrap().is_empty());

        cleanup(&path);
    }

    #[tokio::test]
    async fn auth_user_without_alliance_skips_alliance_lookup() {
        let mut mock = MockEsiApi::new();
        mock.expect_authenticate()
            .times(1)
            .returning(|_, _| Ok(Some(sample_claims())));
        mock.expect_current_tokens()
            .times(1)
            .returning(|| Some(sample_tokens()));
        mock.expect_update_spec().times(1).returning(|| Ok(()));
        mock.expect_get_character_public_info()
            .times(1)
            .returning(|_| {
                Ok(CharacterPublicInfo {
                    corporation_id: 98000001,
                    alliance_id: None,
                })
            });
        mock.expect_get_corporation_public_info()
            .times(1)
            .returning(|_| {
                Ok(Corporation {
                    id: 98000001,
                    name: String::from("Acme Corp"),
                })
            });
        // Without alliance_id the alliance endpoint must not be called.
        mock.expect_get_alliance_info().never();
        mock.expect_get_character_portrait_url()
            .times(1)
            .returning(|_| Ok(String::from("https://images/pilot.png")));
        mock.expect_get_location()
            .times(1)
            .returning(|_| Ok(30000142));
        let (mut manager, path) = mock_manager("auth_no_ally", mock);

        let player = manager
            .auth_user(
                sample_authorize_info(),
                (String::from("oauth-code"), String::from("oauth-state")),
            )
            .await
            .unwrap()
            .expect("a character must be returned");
        assert!(player.alliance.is_none());
        assert_eq!(player.corp.unwrap().name, "Acme Corp");

        cleanup(&path);
    }

    #[tokio::test]
    async fn auth_user_rejects_malformed_sub_claim() {
        let mut mock = MockEsiApi::new();
        mock.expect_authenticate().times(1).returning(|_, _| {
            Ok(Some(AuthClaims {
                name: String::from("Test Pilot"),
                sub: String::from("INVALID-SUBJECT"),
            }))
        });
        let (mut manager, path) = mock_manager("auth_bad_sub", mock);

        // A malformed subject must produce an error, not a panic.
        let result = manager
            .auth_user(
                sample_authorize_info(),
                (String::from("oauth-code"), String::from("oauth-state")),
            )
            .await;
        assert!(result.is_err());

        cleanup(&path);
    }

    #[tokio::test]
    async fn valid_token_matrix() {
        let (mut manager, path) = mock_manager("valid_matrix", MockEsiApi::new());

        // No tokens for that character
        assert!(!manager.valid_token(PILOT).await);

        // Missing expiration
        manager.auth.insert(
            PILOT,
            AuthData {
                token: String::from("access-token"),
                refresh_token: String::from("refresh-token"),
                expiration: None,
            },
        );
        assert!(!manager.valid_token(PILOT).await);

        // Expiring within the 20 second safety window
        authenticate_session(&mut manager, 10);
        assert!(!manager.valid_token(PILOT).await);

        // Valid token, only for that character
        authenticate_session(&mut manager, 3600);
        assert!(manager.valid_token(PILOT).await);
        assert!(!manager.valid_token(1).await);

        cleanup(&path);
    }

    #[test]
    fn remove_characters_also_removes_their_tokens() {
        let (mut manager, path) = test_manager("remove_tokens");
        let conn = manager.get_standard_connection().unwrap();
        for id in [1, 2] {
            let mut character = Character::new();
            character.id = id;
            character.name = format!("Pilot {id}");
            manager.write_character(&character).unwrap();
            PlayerDatabase::save_auth(&conn, id, &AuthData::new()).unwrap();
            manager.auth.insert(id, AuthData::new());
        }

        assert_eq!(manager.remove_characters(Some(vec![1])).unwrap(), 1);
        assert!(!manager.auth.contains_key(&1));
        let stored = PlayerDatabase::select_auth(&conn).unwrap();
        assert!(!stored.contains_key(&1));
        assert!(stored.contains_key(&2));
        cleanup(&path);
    }

    // -----------------------------------------------------------------
    // get_player_photo against a local HTTP server
    // -----------------------------------------------------------------

    /// Spawns a local HTTP server that answers every request with the given
    /// status code and body. Returns its address.
    async fn spawn_photo_server(status: u16, body: &'static [u8]) -> std::net::SocketAddr {
        use http_body_util::Full;
        use hyper::Response;
        use hyper::server::conn::http1;
        use hyper::service::service_fn;
        use hyper_util::rt::TokioIo;
        use tokio::net::TcpListener;

        let listener = TcpListener::bind(std::net::SocketAddr::from(([127, 0, 0, 1], 0)))
            .await
            .unwrap();
        let addr = listener.local_addr().unwrap();
        tokio::spawn(async move {
            while let Ok((stream, _)) = listener.accept().await {
                let io = TokioIo::new(stream);
                tokio::spawn(async move {
                    let service = service_fn(move |_req| {
                        let body = Bytes::from_static(body);
                        async move {
                            Ok::<_, hyper::Error>(
                                Response::builder()
                                    .status(status)
                                    .body(Full::new(body))
                                    .unwrap(),
                            )
                        }
                    });
                    let _ = http1::Builder::new().serve_connection(io, service).await;
                });
            }
        });
        addr
    }

    #[tokio::test]
    async fn get_player_photo_downloads_bytes() {
        let addr = spawn_photo_server(200, b"fake-jpeg-bytes").await;
        let url = format!("http://{addr}/portrait.jpg");

        // get_player_photo creates its own runtime via #[tokio::main], so it
        // must run outside the test runtime context.
        let photo = tokio::task::spawn_blocking(move || {
            EsiManager::get_player_photo(&url).map_err(|e| e.to_string())
        })
        .await
        .unwrap()
        .unwrap();
        assert_eq!(photo, b"fake-jpeg-bytes");
    }

    #[tokio::test]
    async fn get_player_photo_returns_empty_on_error_status() {
        let addr = spawn_photo_server(404, b"not-found").await;
        let url = format!("http://{addr}/portrait.jpg");

        let photo = tokio::task::spawn_blocking(move || {
            EsiManager::get_player_photo(&url).map_err(|e| e.to_string())
        })
        .await
        .unwrap()
        .unwrap();
        assert!(photo.is_empty());
    }
}
