[package]
name = "native_tools"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
profiling = "1.0"

[lints]
workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62.2", features = ["Win32_UI_Shell","Win32_UI_Shell_Common","Win32_System_Com","Win32_Foundation",] }

[target.'cfg(target_os = "linux")'.dependencies]
ashpd = { version = "0.13.12", default-features = false, features = ["file_chooser", "tokio"] }
zbus = { version = "5.18.0", default-features = false, features = ["tokio"] }
rustix = { version = "1.1.4", features = ["process"] }
tokio = { version = "1.47.1", features = ["rt", "macros"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc2-io-kit = { version = "0.3.2", features = ["libc"], default-features = false}
objc2-core-foundation = { version = "0.3.2", features = ["CFString"] }
objc2-foundation = {version = "0.3.2", features = ["NSString"] }
objc2-app-kit = { version = "0.3.2", features = [
    "NSOpenPanel",
    "NSSavePanel",
    "NSPanel",
    "NSWindow",
    "NSResponder",
] }
block2 = "0.6.2"
objc2 = { version = "0.6.4", features = ["objc2-proc-macros"] }